# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'pianinka.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Piano(object):
    def setupUi(self, Piano):
        Piano.setObjectName("Piano")
        Piano.resize(1490, 907)
        self.scrollArea = QtWidgets.QScrollArea(Piano)
        self.scrollArea.setGeometry(QtCore.QRect(40, 80, 1441, 821))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1439, 819))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.del_all = QtWidgets.QPushButton(Piano)
        self.del_all.setGeometry(QtCore.QRect(40, 50, 93, 28))
        self.del_all.setObjectName("del_all")
        self.play_melody = QtWidgets.QPushButton(Piano)
        self.play_melody.setGeometry(QtCore.QRect(1070, 50, 181, 28))
        self.play_melody.setObjectName("play_melody")
        self.cells = QtWidgets.QPushButton(Piano)
        self.cells.setGeometry(QtCore.QRect(980, 50, 93, 28))
        self.cells.setObjectName("cells")
        self.count_cells = QtWidgets.QSpinBox(Piano)
        self.count_cells.setGeometry(QtCore.QRect(920, 50, 61, 31))
        self.count_cells.setMinimumSize(QtCore.QSize(42, 22))
        self.count_cells.setObjectName("count_cells")
        self.YES = QtWidgets.QPushButton(Piano)
        self.YES.setGeometry(QtCore.QRect(1250, 50, 231, 28))
        self.YES.setObjectName("YES")
        self.error = QtWidgets.QTextEdit(Piano)
        self.error.setGeometry(QtCore.QRect(1070, 20, 411, 31))
        self.error.setObjectName("error")

        self.retranslateUi(Piano)
        QtCore.QMetaObject.connectSlotsByName(Piano)

    def retranslateUi(self, Piano):
        _translate = QtCore.QCoreApplication.translate
        Piano.setWindowTitle(_translate("Piano", "Form"))
        self.del_all.setText(_translate("Piano", "удалить всё"))
        self.play_melody.setText(_translate("Piano", "воспроизвести мелодию"))
        self.cells.setText(_translate("Piano", "добавить"))
        self.YES.setText(_translate("Piano", "соxранить мелодию(формат wav)"))
